const LIGHT_THEME = {

    GRID_MOBILE_PORTRAIT_COLUMNS : "4",

    GRID_MOBILE_PORTRAIT_GUTTER : "8px",

    GRID_MOBILE_PORTRAIT_MARGIN : "14px",

    GRID_MOBILE_LANDSCAPE_COLUMNS : "6",

    GRID_MOBILE_LANDSCAPE_GUTTER : "10px",

    GRID_MOBILE_LANDSCAPE_MARGIN : "18px",

    GRID_TABLET_PORTRAIT_COLUMNS : "8",

    GRID_TABLET_PORTRAIT_GUTTER : "12px",

    GRID_TABLET_PORTRAIT_MARGIN : "22px",

    GRID_TABLET_LANDSCAPE_COLUMNS : "12",

    GRID_TABLET_LANDSCAPE_GUTTER : "14px",

    GRID_TABLET_LANDSCAPE_MARGIN : "26px",

    GRID_DESKTOP_COLUMNS : "12",

    GRID_DESKTOP_GUTTER : "16px",

    GRID_DESKTOP_MARGIN : "auto",

    RESPONSIVE_MOBILE_PORTRAIT_MAX : "428px",

    RESPONSIVE_MOBILE_LANDSCAPE_MIN : "429px",

    RESPONSIVE_MOBILE_LANDSCAPE_MAX : "768px",

    RESPONSIVE_TABLET_PORTRAIT_MIN : "769px",

    RESPONSIVE_TABLET_PORTRAIT_MAX : "1024px",

    RESPONSIVE_TABLET_LANDSCAPE_MIN : "1025px",

    RESPONSIVE_TABLET_LANDSCAPE_MAX : "1280px",

    RESPONSIVE_DESKTOP_MIN : "1281px",

    FONT_SIZE_EXTRA_LARGE : "2rem",

    FONT_SIZE_LARGE : "1.5rem",

    FONT_SIZE_MEDIUM : "1rem",

    FONT_SIZE_SMALL : "0.875rem",

    FONT_SIZE_EXTRA_SMALL : "0.625rem",

    FONT_WEIGHT_THIN : "100",

    FONT_WEIGHT_EXTRA_LIGHT : "200",

    FONT_WEIGHT_LIGHT : "300",

    FONT_WEIGHT_NORMAL : "400",

    FONT_WEIGHT_MEDIUM : "500",

    FONT_WEIGHT_SEMI_BOLD : "600",

    FONT_WEIGHT_BOLD : "700",

    FONT_WEIGHT_EXTRA_BOLD : "800",

    FONT_WEIGHT_BLACK : "900",

    LINE_HEIGHT_EXTRA_LARGE : "2",

    LINE_HEIGHT_LARGE : "1.5",

    LINE_HEIGHT_MEDIUM : "1",

    LINE_HEIGHT_SMALL : "0.875",

    LINE_HEIGHT_EXTRA_SMALL : "0.625",

    COLOR_PRIMARY_DEFAULT : "#6750A4",

    COLOR_PRIMARY_ON_DEFAULT : "#FFFFFF",

    COLOR_PRIMARY_CONTAINER : "#EADDFF",

    COLOR_PRIMARY_ON_CONTAINER : "#21005D",

    COLOR_SECONDARY_DEFAULT : "#625B71",

    COLOR_SECONDARY_ON_DEFAULT : "#FFFFFF",

    COLOR_SECONDARY_CONTAINER : "#E8DEF8",

    COLOR_SECONDARY_ON_CONTAINER : "#1D192B",

    COLOR_TERTIARY_DEFAULT : "#7D5260",

    COLOR_TERTIARY_ON_DEFAULT : "#FFFFFF",

    COLOR_TERTIARY_CONTAINER : "#FFD8E4",

    COLOR_TERTIARY_ON_CONTAINER : "#31111D",

    COLOR_ERROR_DEFAULT : "#B3261E",

    COLOR_ERROR_ON_DEFAULT : "#FFFFFF",

    COLOR_ERROR_CONTAINER : "#F9DEDC",

    COLOR_ERROR_ON_CONTAINER : "#410E0B",

    COLOR_BACKGROUND_DEFAULT : "#FFFFFF",

    COLOR_BACKGROUND_ON_DEFAULT : "#1C1B1F",

    COLOR_SURFACE_DEFAULT : "#FFFFFF",

    COLOR_SURFACE_ON_DEFAULT : "#1C1B1F",

    COLOR_SURFACE_VARIANT : "#E7E0EC",

    COLOR_SURFACE_ON_VARIANT : "#49454F",

    COLOR_OUTLINE_DEFAULT : "#79747E",

    COLOR_SUCCESS_DEFAULT : "#388E3C",

    COLOR_SUCCESS_ON_DEFAULT : "#FFFFFF",

    COLOR_SUCCESS_CONTAINER : "#C8E6C9",

    COLOR_SUCCESS_ON_CONTAINER : "#1B5E20",

    COLOR_WARNING_DEFAULT : "#F57C00",

    COLOR_WARNING_ON_DEFAULT : "#FFFFFF",

    COLOR_WARNING_CONTAINER : "#FFE0B2",

    COLOR_WARNING_ON_CONTAINER : "#E65100",

    BORDER_HIDDEN_THIN : "1px hidden",

    BORDER_HIDDEN_MEDIUM : "2px hidden",

    BORDER_HIDDEN_BOLD : "3px hidden",

    BORDER_HIDDEN_BLACK : "4px hidden",

    BORDER_DOTTED_THIN : "1px dotted",

    BORDER_DOTTED_MEDIUM : "2px dotted",

    BORDER_DOTTED_BOLD : "3px dotted",

    BORDER_DOTTED_BLACK : "4px dotted",

    BORDER_DASHED_THIN : "1px dashed",

    BORDER_DASHED_MEDIUM : "2px dashed",

    BORDER_DASHED_BOLD : "3px dashed",

    BORDER_DASHED_BLACK : "4px dashed",

    BORDER_DOUBLE_THIN : "1px double",

    BORDER_DOUBLE_MEDIUM : "2px double",

    BORDER_DOUBLE_BOLD : "3px double",

    BORDER_DOUBLE_BLACK : "4px double",

    BORDER_GROOVE_THIN : "1px groove",

    BORDER_GROOVE_MEDIUM : "2px groove",

    BORDER_GROOVE_BOLD : "3px groove",

    BORDER_GROOVE_BLACK : "4px groove",

    BORDER_RIDGE_THIN : "1px ridge",

    BORDER_RIDGE_MEDIUM : "2px ridge",

    BORDER_RIDGE_BOLD : "3px ridge",

    BORDER_RIDGE_BLACK : "4px ridge",

    BORDER_INSET_THIN : "1px inset",

    BORDER_INSET_MEDIUM : "2px inset",

    BORDER_INSET_BOLD : "3px inset",

    BORDER_INSET_BLACK : "4px inset",

    BORDER_OUTSET_THIN : "1px outset",

    BORDER_OUTSET_MEDIUM : "2px outset",

    BORDER_OUTSET_BOLD : "3px outset",

    BORDER_OUTSET_BLACK : "4px outset",

    BORDER_SOLID_THIN : "1px solid",

    BORDER_SOLID_MEDIUM : "2px solid",

    BORDER_SOLID_BOLD : "3px solid",

    BORDER_SOLID_BLACK : "4px solid",

    BORDER_RADIUS_EXTRA_LARGE : "20px",

    BORDER_RADIUS_LARGE : "16px",

    BORDER_RADIUS_MEDIUM : "12px",

    BORDER_RADIUS_SMALL : "8px",

    BORDER_RADIUS_EXTRA_SMALL : "4px",

    BORDER_RADIUS_FULL : "100%",

    SPACING_EXTRA_LARGE : "24px",

    SPACING_LARGE : "20px",

    SPACING_MEDIUM : "16px",

    SPACING_SMALL : "12px",

    SPACING_EXTRA_SMALL : "8px",

    SHADOW_TOP_LEFT_LARGE : "-12px -12px 20px 2px",

    SHADOW_TOP_LEFT_MEDIUM : "-8px -8px 14px 2px",

    SHADOW_TOP_LEFT_SMALL : "-2px -2px 10px 2px",

    SHADOW_TOP_RIGHT_LARGE : "12px -12px 20px 2px",

    SHADOW_TOP_RIGHT_MEDIUM : "8px -8px 14px 2px",

    SHADOW_TOP_RIGHT_SMALL : "2px -2px 10px 2px",

    SHADOW_BOTTOM_LEFT_LARGE : "-12px 12px 20px 2px",

    SHADOW_BOTTOM_LEFT_MEDIUM : "-8px 8px 14px 2px",

    SHADOW_BOTTOM_LEFT_SMALL : "-2px 2px 10px 2px",

    SHADOW_BOTTOM_RIGHT_LARGE : "12px 12px 20px 2px",

    SHADOW_BOTTOM_RIGHT_MEDIUM : "8px 8px 14px 2px",

    SHADOW_BOTTOM_RIGHT_SMALL : "2px 2px 10px 2px",

    FONT_FAMILY : "맑은 고딕, malgun gothic, AppleGothicNeoSD, Apple SD 산돌고딕 Neo, Microsoft NeoGothic,  Droid sans, sans-serif;",
   
};

export default LIGHT_THEME